# Generated by Django 5.0.6 on 2024-06-12 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_productratingreview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductRatingReview',
            new_name='ProductReview',
        ),
    ]
